#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e

# boot the app and any other necessary processes.
bundle exec jekyll serve --incremental
